# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CMDB', '0003_auto_20171206_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd', models.CharField(max_length=100, verbose_name='Salt命令')),
                ('doc', models.TextField(blank=True, max_length=1000, verbose_name='帮助文档')),
            ],
            options={
                'verbose_name': 'Salt命令',
                'verbose_name_plural': 'Salt命令列表',
            },
        ),
        migrations.CreateModel(
            name='Minions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minion', models.CharField(max_length=50, verbose_name='客户端')),
                ('grains', models.TextField(blank=True, max_length=500, verbose_name='Grains信息')),
                ('pillar', models.TextField(blank=True, max_length=500, verbose_name='Pillar信息')),
                ('status', models.CharField(choices=[('Unknown', 'Unknown'), ('Accepted', 'Accepted'), ('Denied', 'Denied'), ('Unaccepted', 'Unaccepted'), ('Rejected', 'Rejected')], default='Unknown', max_length=20, verbose_name='在线状态')),
            ],
            options={
                'verbose_name': 'Salt客户端',
                'verbose_name_plural': 'Salt客户端列表',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(default='execution', max_length=20, verbose_name='Salt模块类型')),
                ('name', models.CharField(max_length=20, verbose_name='Salt模块名称')),
            ],
            options={
                'verbose_name': 'Salt模块',
                'verbose_name_plural': 'Salt模块列表',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(blank=True, max_length=20, verbose_name='执行方式')),
                ('fun', models.CharField(max_length=50, verbose_name='命令')),
                ('arg', models.CharField(blank=True, max_length=255, verbose_name='参数')),
                ('tgt_type', models.CharField(max_length=20, verbose_name='目标类型')),
                ('jid', models.CharField(blank=True, max_length=50, verbose_name='任务号')),
                ('minions', models.CharField(blank=True, max_length=500, verbose_name='目标主机')),
                ('result', models.TextField(blank=True, verbose_name='返回结果')),
                ('user', models.CharField(max_length=50, verbose_name='操作用户')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
            ],
            options={
                'verbose_name': '命令返回结果',
                'verbose_name_plural': '命令返回结果',
            },
        ),
        migrations.CreateModel(
            name='SaltServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=100, verbose_name='URL地址')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('role', models.CharField(choices=[('Master', 'Master'), ('Backend', 'Backend')], default='Master', max_length=20, verbose_name='角色')),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMDB.IDC', verbose_name='所属机房')),
            ],
            options={
                'verbose_name': 'Salt服务器',
                'verbose_name_plural': 'Salt服务器列表',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(blank=True, max_length=20, verbose_name='执行方式')),
                ('fun', models.CharField(max_length=50, verbose_name='命令')),
                ('arg', models.CharField(blank=True, max_length=255, verbose_name='参数')),
                ('tgt_type', models.CharField(max_length=20, verbose_name='目标类型')),
                ('jid', models.CharField(blank=True, max_length=50, verbose_name='任务号')),
                ('minions', models.CharField(blank=True, max_length=500, verbose_name='目标主机')),
                ('result', models.TextField(blank=True, verbose_name='返回结果')),
                ('user', models.CharField(max_length=50, verbose_name='操作用户')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SALT.SaltServer', verbose_name='所属Salt服务器')),
            ],
            options={
                'verbose_name': '部署结果',
                'verbose_name_plural': '部署结果',
            },
        ),
        migrations.CreateModel(
            name='SvnProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='项目名称')),
                ('host', models.CharField(max_length=50, verbose_name='项目主机')),
                ('path', models.CharField(max_length=200, verbose_name='项目根路径')),
                ('target', models.CharField(max_length=50, verbose_name='项目目录')),
                ('url', models.CharField(max_length=200, verbose_name='SVN地址')),
                ('username', models.CharField(max_length=40, verbose_name='SVN账号')),
                ('password', models.CharField(blank=True, max_length=40, verbose_name='SVN密码')),
                ('status', models.CharField(default='新建', max_length=40, verbose_name='状态')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('info', models.TextField(blank=True, max_length=500, verbose_name='信息')),
                ('salt_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SALT.SaltServer', verbose_name='所属Salt服务器')),
            ],
            options={
                'verbose_name': 'SVN项目',
                'verbose_name_plural': 'SVN项目列表',
            },
        ),
        migrations.AddField(
            model_name='result',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SALT.SaltServer', verbose_name='所属Salt服务器'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=set([('client', 'name')]),
        ),
        migrations.AddField(
            model_name='minions',
            name='salt_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SALT.SaltServer', verbose_name='所属Salt服务器'),
        ),
        migrations.AddField(
            model_name='command',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SALT.Module', verbose_name='所属模块'),
        ),
        migrations.AlterUniqueTogether(
            name='svnproject',
            unique_together=set([('host', 'path', 'target')]),
        ),
        migrations.AlterUniqueTogether(
            name='minions',
            unique_together=set([('minion', 'salt_server')]),
        ),
        migrations.AlterUniqueTogether(
            name='command',
            unique_together=set([('module', 'cmd')]),
        ),
    ]
