# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 14:39
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_name', models.CharField(max_length=100, verbose_name='通知名称')),
                ('detail', DjangoUeditor.models.UEditorField(default='', verbose_name='通知详情')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知列表',
            },
        ),
    ]
