# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MESSAGE', '0002_message_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=20, verbose_name='名字'),
        ),
    ]
